version: '3'
services:
  node-frontend-iptc-app:
    build: ./frontend
    container_name: node-frontend-iptc-app
    ports:
      - 8081:8080
    volumes:
        - ./frontend:/app
        - /app/node_modules

  node-backend-iptc-app:
    build: ./backend
    container_name: node-backend-iptc-app
    ports:
      - 8082:8080